server:
  port: 9000
spring:
  profiles.active: dev

  application:
    name: auth-server # correspond au nom du fichier dans le repo config
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"